export enum LobbyActions {
  CHANGE_USERNAME = 'CHANGE_USERNAME',
  ADD_USER = 'ADD_USER',
  KICK_USER = 'KICK_USER',
  CHANGE_LINK = 'CHANGE_LINK',
  IS_DEALER = 'IS_DEALER',
}

export enum HomeActions {
  CHANGE_AVATAR = 'CHANGE_AVATAR',
}

export enum IssueActions {
  ADD_ISSUE = 'ADD_ISSUE',
  REMOVE_ISSUE = 'REMOVE_ISSUE',
  EDIT_ISSUE = 'EDIT_ISSUE',
  CHANGE_ISSUES = 'CHANGE_ISSUES',
}

export enum SettingsActions {
  CHANGE_SETTINGS = 'CHANGE_SETTINGS',
  ADD_CARD = 'ADD_CARD',
  REMOVE_CARD = 'REMOVE_CARD',
  EDIT_CARD = 'EDIT_CARD',
}
