export enum LobbyActions {
  CHANGE_USERNAME = 'CHANGE_USERNAME',
  ADD_USER = 'ADD_USER',
  KICK_USER = 'KICK_USER',
  CHANGE_LINK = 'CHANGE_LINK',
  IS_DEALER = 'IS_DEALER',
}

export enum HomeActions {
  CHANGE_AVATAR = 'CHANGE_AVATAR',
}
